name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Zip the Lambda function code
    - name: Zip Lambda function
      run: |
        zip lambda_function.zip lambda_function.py
        zip card_val.zip card_val.py
        zip login_page.zip login_page.py
        zip expense_tracker.zip expense_tracker.py

    # Step 3: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 4: Deploy to AWS Lambda
    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name TestFunction \
          --zip-file fileb://lambda_function.zip

        aws lambda update-function-code \
          --function-name CardVal \
          --zip-file fileb://card_val.zip

        aws lambda update-function-code \
          --function-name LoginPage \
          --zip-file fileb://login_page.zip

        aws lambda update-function-code \
          --function-name ExpenseTracker \
          --zip-file fileb://expense_tracker.zip
